devaffair/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from devaffair import views
import settings

urlpatterns = patterns('',
	url(r'^$', views.home, name='home'),
    # Examples:
    # url(r'^$', 'devbears.views.home', name='home'),
    # url(r'^devbears/', include('devbears.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    # url(r'^clubs/', 'devbears.views.clubs', name='clubs')
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/', views.logout, name='logout'),


    #this one must be last so that nothing matches as being a university
    url(r'(?P<university>\w+)/', include('university.urls', namespace='university')),

    
    )

handler403 = 'devaffair.views.handle403'

ucl/urls.py
from django.conf.urls import patterns, include, url
from berkeley import views


urlpatterns = patterns('', 
	url(r'^$', views.index, name='ucl_index'),
	url(r'^clubs/', include('clubs.urls')),
	url(r'^devs/', include('devs.urls')),
	)

university/urls.py
from django.conf.urls import patterns, include, url
from university import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='university_index'),
	url(r'^clubs/', include('clubs.urls', namespace='clubs')),
	url(r'^devs/', include('devs.urls', namespace='devs')),
)

devaffair/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from devaffair.functions import *
import random

def home(request):
	context = {}
	context['request'] = request
	uni_list = get_uni_tuples()
	context['uni_list'] = uni_list
	print uni_list
	return render(request, 'devaffair/index.html', context)

def handle403(request):
	context = {}
	return render(request, 'devaffair/403.html', context)

def logout(request):

	request.session.flush()
	context = {}
	context['error'] = "You have successfully logged out."
	return render(request, 'devaffair/index.html', context)

devaffair/templates/devaffair/base.html
{% load bootstrap_toolkit %}
{% load staticfiles %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  {% bootstrap_stylesheet_tag %}
  {% bootstrap_stylesheet_tag "responsive" %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  {% bootstrap_javascript_tag %}
  <link rel="stylesheet" href='{% static "css/base_style.css" %}'>
  <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
  {% block extra_head_content %} {% endblock %}
</head>

      {% block navbar %}{% endblock %}
      {% block content %}{% endblock %}

devaffair/templates/devaffair/index.html
{% extends "devaffair/base.html" %}
{% load bootstrap_toolkit %}

{% block navbar %}
<div class="navbar-wrapper">
	<!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
	<div class="container">

		<div class="navbar navbar-inverse">
			<div class="navbar-inner">
				<a class="brand" href="/">DevAffair</a>
				{% if request.session.usertoken %}
				<ul class="nav pull-right">
					<li>
						<a href='{% url 'university:clubs:club_profile' university=request.session.university club_id=request.session.id %}'>
							{% if request.session.type == 'club' %}
							<i class="icon-group"></i>
							{% endif %}
							{% if request.session.type == 'dev' %}
							<i class='icon-user'></i>
							{% endif %}
							{{request.session.name}} :: {{request.session.university|title}}</a></li>
							<li><a href="{% url 'logout' %}">Logout</a></li>
						</ul>
						{% endif %}
					</div><!-- /.navbar-inner -->
				</div><!-- /.navbar -->
				{% if error %}
				<div class="center alert alert-error">{{error}}</div>
				{% endif %}
			</div> <!-- /.container -->
		</div><!-- /.navbar-wrapper -->
		{% endblock navbar %}

		{% block content %}
		<div class="container">
			<div class="hero-unit">
				<h1>Devaffair</h1>
				<p>A way for CS students to improve the technology facilities of university societies.</p>
				<ul class='unstyled'>
					{% for short_uni, long_uni in uni_list %}
					<li>
						<a href='{% url 'university:university_index' university=short_uni %}'>{{long_uni}}</a>
					</li>
					{% endfor %}
				</ul>
				<p>
					<a class="btn btn-primary btn-large">
						Learn more
					</a>
				</p>
			</div>

			
		</div>
		{% endblock content %}

devaffair/templates/devaffair/navbar.html
{% extends 'devaffair/base.html' %}

{% block navbar %}
<div class="navbar-wrapper">
  <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
  <div class="container">

    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <a class="brand" href="/">DevAffair</a>
        <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
        <ul class="nav">
          {% if not request.get_full_path = "/" %}
          <li><a href="{% url 'university:clubs:club_index' university=university %}">Clubs</a></li>
          <li><a href="{% url 'university:devs:dev_index' university=university %}">Devs</a></li>
          {% endif %}
        </ul>
        {% if request.session.usertoken %}
        <ul class="nav pull-right">
          <li>
            <a href='{% url 'university:clubs:club_profile' university=university club_id=request.session.id %}'>
              {% if request.session.type == 'club' %}
              <i class="icon-group"></i>
              {% endif %}
              {% if request.session.type == 'dev' %}
              <i class='icon-user'></i>
              {% endif %}
              {{request.session.name}} :: {{university|title}}</a></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
            {% endif %}
          </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->
        {% if error %}
        <div class="center alert alert-error">{{error}}</div>
        {% endif %}
      </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->
    {% endblock %}